MJRefreshExample/MJRefreshExample.xcodeproj/project.pbxproj

根据文档，把这里改成了6.0。这样开发者 clone 后不需要修改工程配置就可以运行 demo了。

Update IPHONEOS_DEPLOYMENT_TARGET to 6.0.

---

MJRefreshExample/MJRefreshExample/MJRefresh/MJRefreshHeader.m

解决问题可以参照
[section-headers-in-uitablevie
w-when-inset-of-tableview-is-changed](http://stackoverflow.com/questions/5466097/section-headers-in-uitablevie
w-when-inset-of-tableview-is-changed) 下拉控件在refreshing 状态，由于 contentInset
的改变，会影响section header 的显示。

refreshing 状态视觉bug修复

---

MJRefreshExample/MJRefreshExample/MJRefresh/MJRefreshFooter.m

在 viewDidLoad 的时候 调用了 addLegendFooterWithRefreshingTarget, 然后 0.3秒内有数据返回, 此时判断了发现 no more data, 调用 noticeNoMoreData, 然后到达0.3秒, self.loadMoreButton.hidden = NO; 被调用, 导致 loadMoreButton 和 noMoreLabel 同时显示.

修复 loadMoreButton 和 noMoreLabel 有时同时显示的问题.

---

MJRefresh/Base/MJRefreshFooter.m

这里可以用传入的totalDataCount，不必再次调用self.scrollView.totalDataCount。
另外，self.scrollView.totalDataCount函数可否优化为：遍历到table有数据即可返回，因为返回的这个totalDataCount值也仅仅是用在这里和0比较，设置self.hidden。（这个PR里暂时没有做这个优化）

去掉重复调用totalDataCount

---

MJRefresh/Custom/Header/MJRefreshStateHeader.m

iOS9最近总是在初始化组件的时候crash。此段兼容性代码在iOS8版本之后使用SDK中较新的API。目前测试crash没再出现。

增加日历获取兼容性代码

---

MJRefresh/Custom/Header/MJRefreshStateHeader.m

NSFoundationVersionNumber_iOS_8_0 这个宏在xcode6.4下没定义

xcode6.4 编译错误

---

MJRefresh/Base/MJRefreshComponent.m

修复当前正在刷新中时调用beginRefreshing方法使得header insert回置失败

修复当前正在刷新中时调用beginRefreshing方法使得header insert回置失败

---

MJRefresh/Custom/Header/MJRefreshNormalHeader.m

修改MJRefreshNormalHeader.arrowView的renderingMode为AlwaysTemplate，使得可以更改下拉箭头图片的颜色
header.arrowView?.tintColor = UIColor.whiteColor().colorWithAlphaComponent(0.7)

修改MJRefreshNormalHeader.arrowView的renderingMode为AlwaysTemplate，使得可以更改下拉箭头图片的颜色

---

MJRefresh/Base/MJRefreshComponent.h
MJRefresh/Base/MJRefreshComponent.m
MJRefresh/Custom/Footer/Auto/MJRefreshAutoStateFooter.m
MJRefresh/Custom/Footer/Back/MJRefreshBackStateFooter.m
MJRefresh/Custom/Header/MJRefreshStateHeader.m

Creating a category for UILabel will cause a duplicated symbol issue in high layer project.
`+ (instancetype)label;`
Added brief prefix for it, please check it.

Renamed the class method in UILabel's category.

---

MJRefresh/Base/MJRefreshHeader.m

修复中途重置 `ignoredScrollViewContentInsetTop` 不及时修改 header.y 的问题，此时 header 早已初始化完成，不会调用 `layoutSubviews` 方法，需要等下拉后才调用该方法去修改 header.y。

`_ignoredScrollViewContentInsetTop` with immediate effect

---

MJRefresh/UIScrollView+MJRefresh.m

OBJC_ASSOCIATION_ASSIGN 会导致系统版本的机型 Crash, 修改为 OBJC_ASSOCIATION_RETAIN

修改 Crash 问题 UIScrollView+MJRefresh.m

---

MJRefresh/UIScrollView+MJExtension.m

目前MJ的这个根据iOS版本判断执行分支代码在大范围的越狱机型方法被hook或者非越狱机型被hook的情况下出现了大范围因 unrecognized selector sent to instance 导致的crash，对这部分代码进行修改，不再判断版本，只判断能否respondsToSelector:

修复MJRefresh中UIScrollView (MJExtension) 根据版本对执行代码的判断逻辑

---

MJRefresh/UIScrollView+MJRefresh.h
MJRefresh/UIScrollView+MJRefresh.m
MJRefreshExample.xcodeproj/project.pbxproj

Hook UITableView&UICollectionView `reloadData`方法容易产生刷新无效的bug，在上一个版本，已经去掉hook相关的代码，方法交换的方法也不需要用上，所以应该删除掉。
Note:
`developmentRegion = English;` ->  `developmentRegion = en;`
仅仅是新版Xcode自动修复的结果，消除编译⚠️

Delete hook UITableView&UICollectionView `reloadData` exchange method code

---

MJRefresh/Base/MJRefreshHeader.m

- 解决 iOS < 10 和 > 10 的顶部留空 bug 的区别对待
#1271

不通过停止刷新方案解决顶部栏 bug (停止刷新逻辑在切换 Window 时不做控制)

---

MJRefresh/Base/MJRefreshComponent.m

修改bug，在scrollview的contentInset的left有值时刷新内容不居中，您已经加了相关逻辑，但未生效。
```
@implementation MJRefreshComponent
- (void)willMoveToSuperview:(UIView *)newSuperview
{
[super willMoveToSuperview:newSuperview];
// 如果不是UIScrollView，不做任何事情
if (newSuperview && ![newSuperview isKindOfClass:[UIScrollView class]]) return;
// 旧的父控件移除监听
[self removeObservers];
if (newSuperview) { // 新的父控件
// 设置宽度
self.mj_w = newSuperview.mj_w;
// 设置位置
self.mj_x = -_scrollView.mj_insetL;
// 记录UIScrollView
_scrollView = (UIScrollView *)newSuperview;
// 设置永远支持垂直弹簧效果
_scrollView.alwaysBounceVertical = YES;
// 记录UIScrollView最开始的contentInset
_scrollViewOriginalInset = _scrollView.mj_inset;
// 添加监听
[self addObservers];
}
}
@end
```
在 ` self.mj_x = -_scrollView.mj_insetL;` 时，`_scrollView` 还没有值，所以 `self.mj_x` 永远是0。不会根据 `scrollView` 的 …

修改bug，`self.mj_x = -_scrollView.mj_insetL` 不生效

---

MJRefresh/Base/MJRefreshComponent.h

`MJRefreshComponentbeginRefreshingCompletionBlock` 
rename to 
`MJRefreshComponentBeginRefreshingCompletionBlock`

Fix begin refreshing block typo

---

MJRefresh/Custom/Footer/Back/MJRefreshBackNormalFooter.m

~在block里使用变量会被block引用，所以这个判断永远无效。应该用self.statue判断，因为这里已经改变了。~
状态改变依赖于现值而不是设置的旧值导致原本的过滤条件失效

修复 BackNormalFooter 从刷新状态被设置为闲置状态动画结束后的过滤判断条件

---

MJRefresh/Base/MJRefreshAutoFooter.h
MJRefresh/Base/MJRefreshAutoFooter.m
MJRefresh/Custom/Footer/Auto/MJRefreshAutoStateFooter.m

相关 issue https://github.com/CoderMJLee/MJRefresh/issues/1307 
简介：MJRefreshAutoStateFooter 添加 triggeredByTapGesture 属性，用于标识是否是通过点击 footer 触发的刷新

修复“设置 onlyRefreshPerDrag 为 YES ， 点击 footer 后未开始刷新(#1307)”的 Bug

---

MJRefresh/Base/MJRefreshHeader.m

Caused by https://github.com/CoderMJLee/MJRefresh/pull/1559/commits/ada9e24 and https://github.com/CoderMJLee/MJRefresh/pull/1559/commits/8dd6e3a

Removed duplicated async method on main queue.

---

MJRefresh/Base/MJRefreshHeader.m

This PR is to improvement fix this crash 
https://github.com/CoderMJLee/MJRefresh/issues/1461
Look compare float equal on not correct in some case 
https://stackoverflow.com/questions/4732645/iphone-objective-c-comparing-doubles-not-working
This debug log has demonstrated this issue
```
if (fabs(self.scrollView.mj_insetT - insetT) > FLT_EPSILON) {
self.scrollView.mj_insetT = insetT;
}else{
if (self.scrollView.mj_insetT != insetT ) {
NSLog(@"_--------- same value dif epsilon %f  %f ", self.scrollView.mj_insetT, insetT);
}
}
```
2023-04-02 10:09:15.886546+0700 App[58013:10076967] _--------- same value dif epsilon 172.333333  172.333333

fixed crash loop infinitive when compare float by using FLT_EPSILON

---

MJRefresh/Base/MJRefreshAutoFooter.m

如果footer设置了ignoredScrollViewContentInsetBottom，当列表【刷新后】才添加footer，并且列表【内容不足一页】时，ignoredScrollViewContentInsetBottom并不会生效：
需要滑动列表才会修正，原因是因为刚添加到列表上时并没有添加ignoredScrollViewContentInsetBottom，修正后就好了：

修复MJRefreshAutoFooter初始化时没有添加底部忽略间距的问题
