MJRefreshExample/MJRefreshExample/MJRefresh/UIScrollView+MJRefresh.h, MJRefreshExample/MJRefreshExample/MJRefresh/UIScrollView+MJRefresh.m
我感觉这样易于理解，将来增加新的 header 类型也能容易一些。
=> Adjust code of property header, gifHeader and legendHeader for scalability.

MJRefreshExample/MJRefreshExample/MJRefresh/UIScrollView+MJRefresh.m
目标 `@property (nonatomic, strong) MJRefreshHeader *header;`，对当前代码无影响。
=> Dev prepare for2.0

MJRefreshExample/MJRefreshExample/MJRefresh/MJRefreshFooter.m
__weak typeof(self) -> __weak __typeof(self)
=> 修正 __weak 弱指针低版本报错的问题

MJRefresh/Base/MJRefreshBackFooter.m, MJRefreshExample/MJRefreshExample/Classes/MJTableViewController.m
现象：如果设置autoChangeAlpha为YES，当state设置为NoMoreData后，状态文字一直不会显示。
=> 修复自动回弹上拉控件的一个显示bug

MJRefresh/Custom/Footer/Back/MJRefreshBackStateFooter.h, MJRefresh/Custom/Footer/Back/MJRefreshBackStateFooter.m
MOD: `MJRefreshBackStateFooter`添加获取指定状态下title的方法
=>  给`MJRefreshBackStateFooter`添加获取指定状态下title的方法

MJRefresh/Custom/Footer/Back/MJRefreshBackNormalFooter.m
=> 这里是不是也应该加上MJRefreshFrameworkSrcName？

MJRefresh/Custom/Header/MJRefreshNormalHeader.m
=> 使用 nil coalescing 减少行数

MJRefresh/Base/MJRefreshFooter.m
是不是该避免其他UIScrollView加上这个属性，比如UIWebView的scrollView
=> 在添加reloadDataBlock之前判断一下

MJRefresh/Base/MJRefreshComponent.h
=> DIY最好super一下？

MJRefresh/Custom/Header/MJRefreshNormalHeader.m
Just a simple word spelling issue.
=> Fixed word spelling at #pragma

MJRefresh/Base/MJRefreshComponent.m
=> 对iOS9国际化添加了一个判断

MJRefresh/Base/MJRefreshHeader.m
开发中遇到的问题。在回到refreshing state过程中，会跳一下。log显示动画在completion时content offset
值不对。在这里https://blog.cnbluebox.com/blog/2015/01/19/shake-in-pull-to-refresh/，找到了解决方法
=> fix ui jumping flaw  when it comes back to refreshing state.

README.md
English version of README
杰哥,四级水准写了个英文版README
😄
=> English version of README

MJRefresh/Base/MJRefreshComponent.m, MJRefresh/Base/MJRefreshFooter.m, MJRefresh/Base/MJRefreshHeader.m, MJRefresh/MJRefreshConst.h
=> 解决因异步到主线程执行，造成self延时释放的问题

MJRefresh/MJRefreshConfig.h, MJRefresh/MJRefreshConfig.m, MJRefresh/NSBundle+MJRefresh.m, MJRefreshExample.xcodeproj/project.pbxproj
默认不设置, 走原有功能.
如果设置后, 走设置后的语言选项
很多情况下, 都会有锁定特定语言或者在App中内部有修改语言的选项. 更加的灵活
=> 添加配置类, 用于修改默认配置, 暂时只加了语言选项

MJRefresh/MJRefresh.bundle/ko.lproj/Localizable.strings, MJRefresh/NSBundle+MJRefresh.m
=> Korean Language

MJRefreshExample.xcodeproj/project.pbxproj
=> 解决了carthage导入框架失败

MJRefresh/Base/MJRefreshAutoFooter.m
=> turn the multi-trigger condition off by default

MJRefresh/Base/MJRefreshHeader.m
=> 修复在 iOS13 上使用自动布局导致的布局数据源异常问题

MJRefresh/Base/MJRefreshAutoFooter.h, MJRefresh/Base/MJRefreshAutoFooter.m, MJRefresh/Custom/Footer/Auto/MJRefreshAutoStateFooter.m
Reverts CoderMJLee/MJRefresh#1308
=> Revert "修复“设置 onlyRefreshPerDrag 为 YES ， 点击 footer 后未开始刷新(#1307)”的 Bug"

MJRefresh/Base/MJRefreshAutoFooter.h, MJRefresh/Base/MJRefreshAutoFooter.m, MJRefresh/Custom/Footer/Auto/MJRefreshAutoStateFooter.m, MJRefreshExample/Classes/Second/MJTableViewController.m
#1363 #1365 #1009
1. Add `autoTriggerTimes` property in AutoFooter
2. Change the trigger method in AutoFooter
3. If `autoTriggerTimes = -1`, triggerTimes is infinite
=> Change the trigger method in AutoFooter.

MJRefresh/Custom/Header/MJRefreshStateHeader.h
=> `lastUpdatedTimeText` param should be nullable

MJRefresh/Base/MJRefreshComponent.m
=> Support attributed text width calculation for UILabel

MJRefresh/Base/MJRefreshBackFooter.m, MJRefresh/Base/MJRefreshComponent.h, MJRefresh/Base/MJRefreshComponent.m, MJRefresh/Base/MJRefreshFooter.h, MJRefresh/Base/MJRefreshFooter.m, MJRefresh/Base/MJRefreshHeader.h, MJRefresh/Base/MJRefreshHeader.m
#844 #225 #737 #227 
- **Solve the mess between default animation and UIViewAnimation in UICollectionView.**
- Rename redundant block type definition.
- Rename animating begin block code.
=> Solve the mess between default animation and UIViewAnimation in UICollectionView

MJRefresh/Base/MJRefreshHeader.m
1、修复在uicollectionviewcell嵌套tableview使用refresh，在刷新的同时，左右滑动，导致刷新结束以后，无法滚动tableview的情况。经多次测试，动画代理回调，并没有进入animationForKey的判断。猜测是首先响应滚动事件，导致动画已经移除，无法进入判断。从而导致无法重置响应触摸事件以及contentoffset。
2、修复代码，经多次暴利测试。暂时没有发现问题
=> fix：修复在uicollectionviewcell嵌套tableview使用refresh，在刷新的同时，左右滑动，导致刷新结束以后，无法滚动tableview的情况

MJRefresh/Custom/Footer/Auto/MJRefreshAutoNormalFooter.m, MJRefresh/Custom/Footer/Back/MJRefreshBackNormalFooter.m, MJRefresh/Custom/Header/MJRefreshNormalHeader.m
Ensure the new iOS 13 activityIndicatorViewStyle is set for all iOS 13 builds.
=> iOS 13 activityIndicatorViewStyle check fix

MJRefreshExample.xcodeproj/project.pbxproj
修复使用Carthage方式集成时编译报错 'MJRefreshNormalTrailer.h' file not found #1459
=> fix(carthage): fix carthage build not find header

MJRefresh/Base/MJRefreshAutoFooter.m, MJRefresh/Base/MJRefreshBackFooter.m, MJRefresh/Base/MJRefreshComponent.h, MJRefresh/Base/MJRefreshComponent.m, MJRefresh/Base/MJRefreshHeader.m, MJRefresh/Base/MJRefreshTrailer.m, MJRefresh/Custom/Footer/Back/MJRefreshBackNormalFooter.m, MJRefresh/Custom/Header/MJRefreshNormalHeader.m, MJRefresh/Custom/Trailer/MJRefreshNormalTrailer.m, MJRefresh/MJRefreshConst.h, MJRefresh/MJRefreshConst.m, MJRefreshExample/Classes/Second/MJCollectionViewController.m
- Now animation duration can be changed. (set 0 to disable animtion)
- Providing a new method to disable all animation(setAnimationDisabled) [Specially for Bugs in UICollectionView]
=> Feature: Now animation duration can be changed

MJRefresh.podspec, MJRefresh/NSBundle+MJRefresh.m, Package.swift, README.md
- Remove `MJ_SPM` macro.
- Remove duplicated `cSettings`
=> Remove unnecessary definition in SPM.

MJRefresh.podspec
https://github.com/CoderMJLee/MJRefresh/issues/1604
=> 修复PrivacyInfo.xcprivacy重复的问题
